# -------------------------------------------------------
# 🧠 TrichMind Docker Compose Override
# Dynamically switches between DEV and PROD behavior
# -------------------------------------------------------

services:
  # 🧠 API Server (Node.js)
  server:
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    command: >
      sh -c "
      if [ \"$NODE_ENV\" = 'production' ]; then
        echo '🚀 Running TrichMind Server in PRODUCTION mode...';
        npm run build && npm start
      else
        echo '🧩 Running TrichMind Server in DEVELOPMENT mode (hot reload)...';
        npm run dev
      fi
      "

  # 🌐 Client (Vite Frontend)
  client:
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_BASE=http://server:8080
      - VITE_APP_NAME=TrichMind
    command: >
      sh -c "
      if [ \"$NODE_ENV\" = 'production' ]; then
        echo '🌐 Serving TrichMind frontend (Production Build)...';
        npm run build && npx serve -s dist -l 5173
      else
        echo '⚡ Starting TrichMind Vite Dev Server (Hot Reload)...';
        npm run dev -- --host
      fi
      "
