FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache python3 make g++

COPY package*.json ./
RUN npm ci

COPY . .
EXPOSE 8080

# assumes: "dev": "ts-node-dev --respawn --transpile-only src/server.ts"
CMD ["npm", "run", "dev"]
